# Generated by Django 5.1.7 on 2025-03-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(blank=True, max_length=100, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Окрас'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='health_status',
            field=models.TextField(verbose_name='Состояние здоровья'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='is_adopted',
            field=models.BooleanField(default=False, verbose_name='Усыновлен'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cats/', verbose_name='Фотография'),
        ),
    ]
